export const ESPECIALIDADES_MEDICAS = [
  "CIRURGIA CABECA E PESCOCO", "CIRURGIA GERAL", "CIRURGIA TORACICA",
  "CIRURGIA VASCULAR", "CLINICA GERAL", "HEMATOLOGIA", "INTENSIVISTA",
  "NEFROLOGIA", "NEUROCIRURGIA", "NEUROLOGIA", "ODONTOLOGIA C.TRAUM.B.M.F.",
  "ONCOLOGIA CIRURGICA", "ONCOLOGIA CLINICA/CANCEROLOGIA",
  "ORTOPEDIA/TRAUMATOLOGIA", "PROCTOLOGIA", "UROLOGIA", 'BUCOMAXILO', 'HEPATOLOGISTA', 'MASTOLOGIA', 'RESIDENTE'
];

export const PAGINAS_SISTEMA = [
  'Mapa de Leitos',
  'Regulação de Leitos',
  'Gestão de Isolamentos',
  'Central de Higienização',
  'Auditoria',
];
